sudo: required

services:
  - docker
  
before_install:
  - docker build -t ngs-course-gu .
  - docker ps -a
  
script:
  - echo 'rmarkdown::render("functional_annotation.Rmd")' | R --vanilla
  
# push output to gh-pages

