language: general

sudo: required

services:
  - docker
  
before_install:
  - docker build -t ngs-course-gu .
  - docker ps -a
  
script:
  - docker run ngs-course-gu Rscript -e 'rmarkdown::render("functional_annotation.Rmd")'
  
# push output to gh-pages

